planner-app/config/routes.rb
Rails.application.routes.draw do
  resources :task_groups do
    resources :tasks, except: %i[index show]
  end

  root "task_groups#index"
end

planner-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

planner-app/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_group

  validates :title, presence: true

  scope :completed, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
end

planner-app/app/models/task_group.rb
class TaskGroup < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

planner-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

planner-app/app/controllers/task_groups_controller.rb
class TaskGroupsController < ApplicationController
  before_action :set_task_group, except: [:index]

  def index
    @task_groups = TaskGroup.all
  end

  def create
    if @task_group.save
      redirect_to(
        task_group_url(@task_group),
        notice: "Task group was successfully created."
      )
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task_group.update(task_group_params)
      redirect_to(
        task_group_url(@task_group),
        notice: "Task group was successfully updated."
      )
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task_group.destroy!
    redirect_to task_groups_url, notice: "Task group was successfully destroyed."
  end

  private

  def task_group_params
    params.require(:task_group).permit(:title)
  end

  def set_task_group
    @task_group = if params[:id]
                    TaskGroup.find(params[:id])
                  elsif action_name == "create"
                    TaskGroup.new(task_group_params)
                  else
                    TaskGroup.new
                  end
  end
end

planner-app/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task_group
  before_action :set_task

  def create
    if @task.save
      redirect_to(
        task_group_url(@task_group),
        notice: "Task was successfully created."
      )
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      redirect_to(
        task_group_url(@task_group),
        notice: "Task was successfully updated."
      )
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy!
    redirect_to(
      task_group_url(@task_group),
      notice: "Task was successfully destroyed."
    )
  end

  private

  def set_task_group
    @task_group = TaskGroup.find(params[:task_group_id])
  end

  def set_task
    @task = if params[:id]
              @task_group.tasks.find(params[:id])
            elsif action_name == "create"
              @task_group.tasks.new(task_params)
            else
              @task_group.tasks.new
            end
  end

  def task_params
    params.require(:task).permit(:title, :due_at, :completed)
  end
end

planner-app/app/helpers/application_helper.rb
module ApplicationHelper
end

planner-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <div class="container">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

planner-app/app/views/task_groups/_form.html.erb
<%= form_with(model: task_group) do |form| %>
  <% if task_group.errors.any? %>
    <% task_group.errors.each do |error| %>
      <div class="alert alert-danger" role="alert">
        <%= error.full_message %>
      </div>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label "%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

planner-app/app/views/task_groups/edit.html.erb
<h1>Editing task group</h1>

<%= render "form", task_group: @task_group %>

<div class="mt-3">
  <%= link_to(
        "Cancel",
        @task_group,
        class: "btn btn-outline-secondary"
      ) %>
  <%= button_to(
        "Destroy this task group",
        @task_group,
        method: :delete,
        class: "btn btn-danger mt-5",
        data: { turbo_confirm: "Are you sure?" }
      ) %>
</div>

planner-app/app/views/task_groups/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Task Groups</h1>

  <%= link_to(
        "New task group",
        new_task_group_path,
        class: "btn btn-outline-secondary"
      ) %>
</div>

<div class="list-group mt-5">
  <% @task_groups.each do |task_group| %>
    <%= link_to(
          task_group,
          class: "list-group-item list-group-item-action"
        ) do %>
      <%= task_group.title %>

      <span class="badge bg-warning rounded-pill">
        <%= task_group.tasks.incomplete.count %> incomplete
      </span>

      <span class="badge bg-success rounded-pill">
        <%= task_group.tasks.completed.count %> complete
      </span>
    <% end %>
  <% end %>
</div>

planner-app/app/views/task_groups/new.html.erb
<h1>New task group</h1>

<%= render "form", task_group: @task_group %>

<div>
  <%= link_to "Back to task groups", task_groups_path %>
</div>

planner-app/app/views/task_groups/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1><%= @task_group.title %></h1>

  <%= link_to(
        "Edit task group",
        edit_task_group_path(@task_group),
        class: "btn btn-outline-secondary"
      ) %>
</div>

<div class="mt-5">
  <div class="mb-3">
    <%= link_to "New task", new_task_group_task_path(@task_group), class: "btn btn-primary" %>
  </div>

  <div class="list-group">
    <%= render @task_group.tasks, task_group: @task_group %>
  </div>
</div>

planner-app/app/views/tasks/_form.html.erb
<%= form_with(model: [task_group, task]) do |form| %>
  <% if task.errors.any? %>
    <% task.errors.each do |error| %>
      <div class="alert alert-danger" role="alert">
        <%= error.full_message %>
      </div>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label "%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :due_at, class: "form-label" %>
    <%= form.datetime_field :due_at, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

planner-app/app/views/tasks/_task.html.erb
<%= tag.div(
  class: class_names(
    "list-group-item d-flex justify-content-between align-items-center",
    "list-group-item-success": task.completed
  )
) do %>
  <div>
    <h2><%= task.title %></h2>

    <% if task.due_at %>
      <p class="text-muted"><%= task.due_at %></p>
    <% end %>
  </div>

  <div class="d-flex">
    <% if task.completed %>
      <%= button_to(
            "Incomplete",
            [task_group, task],
            method: :patch,
            class: "btn btn-outline-secondary",
            params: { task: { completed: false } }
          ) %>
    <% else %>
      <%= button_to(
            "Complete",
            [task_group, task],
            method: :patch,
            class: "btn btn-outline-success",
            params: { task: { completed: true } }
          ) %>
    <% end %>

    <%= link_to(
          "Edit",
          edit_task_group_task_path(task_group, task),
          class: "btn btn-link"
        ) %>
  </div>
<% end %>

planner-app/app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task_group: @task_group, task: @task %>

<div class="mt-3">
  <%= link_to "Cancel", @task_group, class: "btn btn-outline-secondary" %>

  <%= button_to(
        "Destroy this task",
        [@task_group, @task],
        method: :delete,
        class: "btn btn-danger mt-5",
        data: { turbo_confirm: "Are you sure?" }
      ) %>
</div>

planner-app/app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task_group: @task_group, task: @task %>

<div>
  <%= link_to "Back to tasks", task_group_path(@task_group) %>
</div>